site_name: URSSI Package Documentation
site_url: https://slahrichi.github.io/urssi-package/
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expandable